#!/bin/bash

scriptdir=`dirname $0`
pushd $scriptdir > /dev/null
scriptdir=`pwd`
popd > /dev/null

op=$1
port=$2

INSTANCEDIR=$scriptdir/target/gemfire/locator

if [ "x$port" == "x" ]; then
	echo "Locator port not specified, using default 40404"
	port=40404
fi

case $op in
	"start")
		echo "Starting locator $INSTANCEDIR"
		echo "checking $INSTANCEDIR/locator${port}state.dat"
		
		if [ -f "$INSTANCEDIR/locator${port}state.dat" ]; then
			echo "Locator $INSTANCEDIR is already running"
			exit 1
		fi
		
		rm -rf $INSTANCEDIR

		if [ ! -d "$INSTANCEDIR" ]; then
			echo "Creating $INSTANCEDIR"
			mkdir -p $INSTANCEDIR
		fi
				
		gemfire start-locator -peer=true -server=true -dir=$INSTANCEDIR -port=$port -Dgemfire.mcast-port=0
		exit 0
		;;
	"stop")
		if [ ! -d "$INSTANCEDIR" ]; then
			echo "Locator $INSTANCEDIR is already stopped"
			exit 1
		fi
	
		echo "Stopping locator $INSTANCEDIR"
		gemfire stop-locator -dir=$INSTANCEDIR -port=$port
		rm -rf $INSTANCEDIR
		exit 0
		;;		
	-*)
		echo "$program: $arg: unknown option"
		exit 1
		;;
	*)
	args="$args $arg"
esac
