#!/bin/bash

scriptdir=`dirname $0`
pushd $scriptdir > /dev/null
scriptdir=`pwd`
popd > /dev/null

mvn clean package

$scriptdir/locator start
$scriptdir/cache start server1
$scriptdir/cache start server2

java -classpath "./application/target/*" starbucks.client.StarbucksApp

