#!/bin/bash

scriptdir=`dirname $0`
pushd $scriptdir > /dev/null
scriptdir=`pwd`
popd > /dev/null

mvn package

$scriptdir/locator start
$scriptdir/cache start server1 &
$scriptdir/cache start server2 &
$scriptdir/cache start server3
